### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by roaldarbol** [roaldarbol/animovement#13]
There's a few things that need to be updated for the docs, but it's almost there.

- [x] Order of articles in `_pkgdown`
- [x] Re-write `Read trackball files` to reflect the current syntax
- [x] Finalise `Calculate kinematics` and `Calculate movement statistics`
- [ ] Switch to Quarto (`.qmd`) format to allow for admonitions

**Comment by roaldarbol** [comment]
Outdated, make specific issues for the specific docs updates.
